services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:     game_news
      POSTGRES_PASSWORD: secret
      POSTGRES_DB:       game_news_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://game_news:secret@db:5434/game_news_db
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  postgres_data: